name: Auto build and push docker containers

on:
  schedule:
    - cron: '45 6 * * *' # https://crontab.guru/#45_6_*_*_* “At 06:45.”
    - cron: '45 18 * * *' # https://crontab.guru/#45_18_*_*_* “At 18:45.”
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./alpine/Dockerfile -t alpinebase/img:alpine -t alpinebase/img:latest .
          docker push alpinebase/img:alpine
          docker push alpinebase/img:latest

  curl:
    needs: alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./curl/Dockerfile -t alpinebase/img:curl .
          docker push alpinebase/img:curl

  imagemagick:
    needs: alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./imagemagick/Dockerfile -t alpinebase/img:imagemagick .
          docker push alpinebase/img:imagemagick

  nginx:
    needs: alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./nginx/Dockerfile -t alpinebase/img:nginx .
          docker push alpinebase/img:nginx

  php_nginx_83:
    needs: nginx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./php-nginx/8.3/Dockerfile -t alpinebase/img:php-nginx-8.3 .
          docker push alpinebase/img:php-nginx-8.3

  php_nginx_83_dev:
    needs: php_nginx_83
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./php-nginx/8.3-dev/Dockerfile -t alpinebase/img:php-nginx-8.3-dev .
          docker push alpinebase/img:php-nginx-8.3-dev

  php_nginx_82:
    needs: nginx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./php-nginx/8.2/Dockerfile -t alpinebase/img:php-nginx-8.2 .
          docker push alpinebase/img:php-nginx-8.2

  php_nginx_82_dev:
    needs: php_nginx_82
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./php-nginx/8.2-dev/Dockerfile -t alpinebase/img:php-nginx-8.2-dev .
          docker push alpinebase/img:php-nginx-8.2-dev

  trivy_vulnerability_scan:
    needs: [alpine, curl, imagemagick, nginx, php_nginx_83, php_nginx_83_dev, php_nginx_82, php_nginx_82_dev]
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [alpine, curl, imagemagick, nginx, php-nginx-8.3, php-nginx-8.3-dev, php-nginx-8.2, php-nginx-8.2-dev]
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:${{ matrix.tag }}
          format: 'sarif'
          output: 'trivy-results.${{ matrix.tag }}.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.${{ matrix.tag }}.sarif'
