name: Auto build and push docker containers

on:
  schedule:
    - cron: '45 1 * * *' # https://crontab.guru/#45_1_*_*_* “At 01:45.”
    - cron: '45 13 * * *' # https://crontab.guru/#45_13_*_*_* “At 13:45.”
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

#######################################################################################

  alpine:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./alpine/Dockerfile -t alpinebase/img:alpine -t alpinebase/img:latest .
          docker push alpinebase/img:alpine
          docker push alpinebase/img:latest
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:alpine
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

#######################################################################################

  curl:
    needs: alpine
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./curl/Dockerfile -t alpinebase/img:curl .
          docker push alpinebase/img:curl
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:curl
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

#######################################################################################

  imagemagick:
    needs: alpine
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./imagemagick/Dockerfile -t alpinebase/img:imagemagick .
          docker push alpinebase/img:imagemagick
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:imagemagick
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

#######################################################################################

  nginx:
    needs: alpine
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./nginx/Dockerfile -t alpinebase/img:nginx .
          docker push alpinebase/img:nginx
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:nginx
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

#######################################################################################

  php_nginx_83:
    needs: nginx
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./php-nginx/8.3/Dockerfile -t alpinebase/img:php-nginx-8.3 .
          docker push alpinebase/img:php-nginx-8.3
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:php-nginx-8.3
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

#######################################################################################

  php_nginx_83_dev:
    needs: php_nginx_83
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u alpinebase --password-stdin
          docker build --no-cache --pull -f ./php-nginx/8.3-dev/Dockerfile -t alpinebase/img:php-nginx-8.3-dev .
          docker push alpinebase/img:php-nginx-8.3-dev
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpinebase/img:php-nginx-8.3-dev
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

#######################################################################################
