name: Daily auto build and push docker images

# Note: the use of "if: always()"
#  A job can require a job to run first (with 'needs'). That job may fail if there are vulnerabilities found.
#  If the previous job has failed, then that job did NOT push a new image to Docker Hub (perhaps it had new vulnerabilities, so we don't want that in Docker Hub)
#  Just continue building the next image, because each build will pull the 'FROM_IMAGE' from Docker Hub (so that's an existing/older image without new known vulnerabilities)

on:
  schedule:
    # Note: This is UTC time
    - cron: '45 8 * * *' # https://crontab.guru/#45_8_*_*_* “At 08:45.”
    - cron: '45 20 * * *' # https://crontab.guru/#45_20_*_*_* “At 20:45.”
  workflow_dispatch:
  push:


permissions:
  contents: read
  actions: read
  security-events: write


jobs:


  ######################### alpine ##############################

  alpine:
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./alpine/Dockerfile
      FROM_IMAGE: 'alpine:latest'
      IMAGE_NAME: 'alpine'
      IMAGE_TAG_SPECIFIC: 'latest'
      IMAGE_TAG_ALIAS: ''
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  alpine_3_19:
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./alpine/Dockerfile
      FROM_IMAGE: 'alpine:3.19'
      IMAGE_NAME: 'alpine'
      IMAGE_TAG_SPECIFIC: '3.19'
      IMAGE_TAG_ALIAS: ''
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  ######################### imagemagick #########################

  imagemagick:
    needs: alpine
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./alpine/Dockerfile
      FROM_IMAGE: 'usethis/alpine:latest'
      IMAGE_NAME: 'imagemagick'
      IMAGE_TAG_SPECIFIC: 'latest'
      IMAGE_TAG_ALIAS: ''
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  ######################### nginx ###############################

  nginx_1:
    needs: alpine
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./nginx/1/Dockerfile
      FROM_IMAGE: 'usethis/alpine:latest'
      IMAGE_NAME: 'nginx'
      IMAGE_TAG_SPECIFIC: '1'
      IMAGE_TAG_ALIAS: ''
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Only for PHP8.1, may be removed at any time, you should upgrade: https://www.php.net/supported-versions.php
  nginx_1_3_19:
    needs: alpine_3_19
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./nginx/1/Dockerfile
      FROM_IMAGE: 'usethis/alpine:3.19'
      IMAGE_NAME: 'nginx'
      IMAGE_TAG_SPECIFIC: '1-3.19'
      IMAGE_TAG_ALIAS: ''
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  ######################### php-nginx ###########################

  php_nginx_83_1:
    needs: nginx_1
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./php-nginx/php8.3-nginx1/Dockerfile
      FROM_IMAGE: 'usethis/nginx:1'
      IMAGE_NAME: 'php-nginx'
      IMAGE_TAG_SPECIFIC: '8.3.1'
      IMAGE_TAG_ALIAS: '8.3'
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  php_nginx_82_1:
    needs: nginx_1
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./php-nginx/php8.2-nginx1/Dockerfile
      FROM_IMAGE: 'usethis/nginx:1'
      IMAGE_NAME: 'php-nginx'
      IMAGE_TAG_SPECIFIC: '8.2.1'
      IMAGE_TAG_ALIAS: '8.2'
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # PHP8.1, may be removed at any time, you should upgrade: https://www.php.net/supported-versions.php
  php_nginx_81_1:
    needs: nginx_1_3_19
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./php-nginx/php8.1-nginx1/Dockerfile
      FROM_IMAGE: 'usethis/nginx:1-3.19'
      IMAGE_NAME: 'php-nginx'
      IMAGE_TAG_SPECIFIC: '8.1.1'
      IMAGE_TAG_ALIAS: '8.1'
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  ######################### php-nginx (dev) #####################

  php_nginx_83_1_dev:
    needs: php_nginx_83_1
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./php-nginx/php8.3-nginx1-dev/Dockerfile
      FROM_IMAGE: 'usethis/php-nginx:8.3.1'
      IMAGE_NAME: 'php-nginx'
      IMAGE_TAG_SPECIFIC: '8.3.1-dev'
      IMAGE_TAG_ALIAS: '8.3-dev'
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  php_nginx_82_1_dev:
    needs: php_nginx_82_1
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./php-nginx/php8.2-nginx1-dev/Dockerfile
      FROM_IMAGE: 'usethis/php-nginx:8.2.1'
      IMAGE_NAME: 'php-nginx'
      IMAGE_TAG_SPECIFIC: '8.2.1-dev'
      IMAGE_TAG_ALIAS: '8.2-dev'
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # PHP8.1, may be removed at any time, you should upgrade: https://www.php.net/supported-versions.php
  php_nginx_81_1_dev:
    needs: php_nginx_81_1
    uses: ./.github/workflows/reusable-docker-build-scan-push.yml
    if: always()
    with:
      DOCKERFILE: ./php-nginx/php8.1-nginx1-dev/Dockerfile
      FROM_IMAGE: 'usethis/php-nginx:8.1.1'
      IMAGE_NAME: 'php-nginx'
      IMAGE_TAG_SPECIFIC: '8.1.1-dev'
      IMAGE_TAG_ALIAS: '8.1-dev'
      DOCKERHUB_USERNAME: usethis
    secrets:
      SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
