name: shared-build-scan-push-docker-image
on:
  workflow_call:
    inputs:
      FROM_IMAGE:
        default: 'alpine:latest'
        description: Base Image
        type: string
        required: true
      DOCKERFILE:
          description: Path to Dockerfile
          type: string
          required: true
      IMAGE_NAME:
        default: 'mytargetimage'
        description: Target image name
        type: string
        required: true
      IMAGE_TAG_SPECIFIC:
        default: '0.1'
        description: Target image tag (specific)
        type: string
        required: true
      IMAGE_TAG_ALIAS:
        default: ''
        description: Target image tag alias, like 'php-nginx:8.3' for 'php-nginx:8.3-1' (php8.3.*, nginx1.*)
        type: string
        required: false
    secrets:
      SECRET_DOCKERHUB_USERNAME:
        required: true
      SECRET_DOCKERHUB_TOKEN:
        required: true

# permissions:
#   contents: read
#   id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - run: |
          echo "${{ secrets.SECRET_DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.SECRET_DOCKERHUB_USERNAME }} --password-stdin

          docker images
          docker build --no-cache --pull --build-arg FROM_IMAGE=${{ inputs.FROM_IMAGE }} -f ${{ inputs.DOCKERFILE }} -t usethis/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG_SPECIFIC }} .
          docker images

          # Tag for Docker Scout repo (all scans in 1 place: usethis/alias:{images-tags} )
          docker tag usethis/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG_SPECIFIC }} usethis/alias:${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_TAG_SPECIFIC }}
          docker images

      - name: Tag alias
        if: ${{ inputs.IMAGE_TAG_ALIAS }} != ''
        run: |
          docker images
          docker tag usethis/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG_SPECIFIC }} usethis/usethis/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG_ALIAS }}
          docker images

  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker images

  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker images
